### ISSUE TITLE
HacktoberFest-Participants

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [sanjulamadurapperuma/HacktoberFest-Participants#1]
Calling all beginner HacktoberFest-Participants! An easy entry for you! All you have to do is to edit the README.md file. Read that file for more information.

**Comment by jonathanfilbert** [comment]
but this issue doesn't have the hacktoberfest label on it..

**Comment by sanjulamadurapperuma** [comment]
@jonathanfilbert Sorry about that, I have added it now. Thanks for pointing it out. :) 💯

**Comment by sanjulamadurapperuma** [comment]
Thank you everyone who contributed to this Hacktoberfest project! Hope this helped you to reach the goal of 4 pull requests! I will be hosting this in the future as well. So stay tuned!
