### ISSUE TITLE
Delete a merge

### ISSUE THREAD

**Issue by netsudo** [sanjulamadurapperuma/HacktoberFest-Participants#32]
Just wondering if you could check your email, I sent you a message regarding this repo. Thanks!

**Comment by netsudo** [comment]
Bump

**Comment by netsudo** [comment]
Bump

**Comment by sanjulamadurapperuma** [comment]
Sorry @netsudo it does not seem like i have got a mail from you. Closing issue since it's over a year now. Let me know if there is anything I can help you with :)
